wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1632609591
    t:
      1:
      - 5
      2:
      - 5
      4: 3.8.10
      5: 0.12.1
      8:
      - 5
